### ISSUE TITLE
fix bug in delete

### ISSUE THREAD

**Issue by BranAndSceolan** [BranAndSceolan/SSE-Notes#54]
> env $(cat ../.testenv) mocha -r ts-node/register tests/chai/index.ts
Server is listening on http://localhost:8000
  Base Route Test
    ✔ should return Welcome to SSE-NOTES!
Time Fri Jul 22 2022 10:48:47 GMT+0000 (Coordinated Universal Time)
$argon2id$v=19$m=65536,t=3,p=1$1hWRtwrGd1HpsxuNhwWK1g$/S6H+mtDRIvmiJ8s/CrDo64PhHGrduX5dI9HjCDZ2vN1M44bYyMV7evUm0HlcxQiwTQ
    ✔ user:register: should return 200 (217ms)
At register : Missing name
    ✔ user:register: missing name. Should return 400
At register : Missing password
    ✔ user:register: missing password. Should return 400
At register, namecheck : This name isn't available!
This name isn't available!
    ✔ user:register: name already in use. Should return 400
At checkLogin : Not logged in, no signInId given.
    ✔ user:logout: should return 200 and other requests should fail
Logged in!
[+] added note with id: 1
Logged in!
    ✔ user:login (210ms)
[+] added note with id: 2
    ✔ documents:create should return 200
At create Note : Title is missing
    ✔ documents:create. title missing. should return 400
At create Note : Content is missing
    ✔ documents:create. content missing. should return 400
At create Note : Privacy flag is missing or invalid
    ✔ documents:create. content missing. should return 400
At create Note : Content is missing
    ✔ documents:create. content wrong datatype. should return 400
At create Note : Title is missing
    ✔ documents:create. wrong datatype in title. should return 400
At create Note : Title is missing
    ✔ documents:create. wrong datatype in privacy flag. should return 400
{
  id: '1',
  title: 'This should succeed',
  content: 'We are logged in',
  private: false,
  authorid: 1,
  name: 'aea61b4f91868b3894c91dd841dc03596e9efd331c893e15ca8c4e27a16de5de6cef9f90358bc8a35e837bfa16596109bd9d60a6e49809c170a2316a3f7a0eb5',
  password: '$argon2id$v=19$m=65536,t=3,p=1$1hWRtwrGd1HpsxuNhwWK1g$/S6H+mtDRIvmiJ8s/CrDo64PhHGrduX5dI9HjCDZ2vN1M44bYyMV7evUm0HlcxQiwTQ'
}
    ✔ documents:get. (own public note) should return 200
    ✔ documents:List should return 200
    1) user:delete. should return 200 and delete as well as log out user
1user aea61b4f91868b3894c91dd841dc03596e9efd331c893e15ca8c4e27a16de5de6cef9f90358bc8a35e837bfa16596109bd9d60a6e49809c170a2316a3f7a0eb5 deleted!
in github actions
exit successfully
finished
    ✔ result for github actions
  17 passing (569ms)
  1 failing
  1) Base Route Test
       user:delete. should return 200 and delete as well as log out user:
     Uncaught Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
      at new NodeError (node:internal/errors:387:5)
      at ServerResponse.setHeader (node:_http_outgoing:603:11)
      at ServerResponse.header (node_modules/express/lib/response.js:794:10)
      at ServerResponse.append (node_modules/express/lib/response.js:755:15)
      at ServerResponse.res.cookie (node_modules/express/lib/response.js:884:8)
      at ServerResponse.clearCookie (node_modules/express/lib/response.js:827:15)
      at Immediate.<anonymous> (modules/controllers/user.controller.ts:12:21)
      at processImmediate (node:internal/timers:471:21)
$argon2id$v=19$m=65536,t=3,p=1$OF1gx+nBkHHD5ay6GGXlrg$BG1GmdSg5v4EkLIhLCTFwnj15Z8+6hnBZqLt5bng2C4jvJB3lkokeB/WE+46qmYTMEA
2user aea61b4f91868b3894c91dd841dc03596e9efd331c893e15ca8c4e27a16de5de6cef9f90358bc8a35e837bfa16596109bd9d60a6e49809c170a2316a3f7a0eb5 deleted!
3user aea61b4f91868b3894c91dd841dc03596e9efd331c893e15ca8c4e27a16de5de6cef9f90358bc8a35e837bfa16596109bd9d60a6e49809c170a2316a3f7a0eb5 deleted!
At checkLogin : Not logged in, no signInId given.
4user aea61b4f91868b3894c91dd841dc03596e9efd331c893e15ca8c4e27a16de5de6cef9f90358bc8a35e837bfa16596109bd9d60a6e49809c170a2316a3f7a0eb5 deleted!
/home/runner/work/SSE-Notes/SSE-Notes/backend/node_modules/mocha/lib/runner.js:950
    throw err;
    ^
Error: done() called multiple times in test <Base Route Test user:delete. should return 200 and delete as well as log out user> of file /home/runner/work/SSE-Notes/SSE-Notes/backend/tests/chai/index.ts
    at createMultipleDoneError (/home/runner/work/SSE-Notes/SSE-Notes/backend/node_modules/mocha/lib/errors.js:428:13)
    at multiple (/home/runner/work/SSE-Notes/SSE-Notes/backend/node_modules/mocha/lib/runnable.js:290:24)
    at done (/home/runner/work/SSE-Notes/SSE-Notes/backend/node_modules/mocha/lib/runnable.js:301:14)
    at /home/runner/work/SSE-Notes/SSE-Notes/backend/node_modules/mocha/lib/runnable.js:371:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_MOCHA_MULTIPLE_DONE',
  valueType: 'undefined',
  value: undefined
}
Node.js v18.6.0
Error: Process completed with exit code 7.

find where this happened in delete:  Uncaught Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
and fix it

**Comment by BranAndSceolan** [comment]
might have been fixed in #62
